apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  # container replications
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      # Service uses to grab which pod
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: t3-app
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

--- 

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  # this is to expose random node endpoint
  type: NodePort
  selector:
    # selects pod from labels object from Deployment
    app: myapp
  ports:
  # where it will be listening
  - port: 80
    # gets info from port 80 and sends to port 8080
    targetPort: 3000

